from __future__ import annotations


REMOTE_TRANSFER_FORMAT_VERSION = 3
LEGACY_REMOTE_TRANSFER_FORMAT_VERSION = 2
LOCAL_BASELINE_STATE_VERSION = 2
SYNC_INDEX_FILENAME = "sync-index.json"
TRANSFER_TASKS_DIRNAME = "tasks"
LEGACY_TRANSFER_CONVERSATIONS_DIRNAME = "conversations"
