"""Deterministic, synthetic allowance fixture generated by the shared renderer."""
from datetime import UTC, datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

from codex_usage.allowance_estimation import estimate_window
from codex_usage.allowance_models import QuotaObservation
from codex_usage.allowance_windows import AllowanceWindow
from codex_usage.report_allowance import allowance_css, render_allowance_section


def allowance_fixture():
    windows = []
    for index, value in enumerate((1180, 1240, 1220, 1260, 1250)):
        start = datetime(2026, 8, 1, tzinfo=UTC) + timedelta(days=index * 7)
        points = [QuotaObservation((start + timedelta(hours=i * 12)).isoformat(), "codex", "primary", "pro", i * 5, 10080,
                                   int((start + timedelta(days=7)).timestamp())) for i in range(13 if index < 4 else 5)]
        window = AllowanceWindow(points, "scheduled-compatible" if index < 4 else "ongoing")
        estimate = estimate_window(window, [p.used_percent * value / 100 for p in points], fully_priced=True)
        windows.append({"limit_id": "codex", "plan": "pro", "duration_minutes": 10080,
                        "start": points[0].timestamp, "end": points[-1].timestamp,
                        "completed": window.completed, "closure": window.closure, "corrections": 0,
                        "estimate": estimate.to_dict(), "points": [dict(p.to_dict(), provenance="Recovered") for p in points]})
    active = windows[-1]["points"][-1]
    return {"status": {"plan": "pro", "active_buckets": [active, dict(active, limit_id="extra-model", used_percent=8, duration_minutes=300)],
                       "probe_status": "fresh", "last_probe_at": active["timestamp"],
                       "lifetime_tokens": 900000000,
                       "recovery": {"total": 80, "complete": 72, "pending": 8, "unavailable": 0}},
            "windows": windows, "qualified": windows[:4], "headline": windows[-1]}


def write_fixture(root: Path):
    import json
    target = root / "apps/desktop/src/allowanceFixture.ts"
    markup = render_allowance_section(
        allowance_fixture(), timezone=ZoneInfo("America/Toronto")
    )
    target.write_text("// Generated by scripts/allowance_fixture.py; synthetic data only.\n"
                      + "export const allowanceHtml = " + json.dumps(markup) + ";\n"
                      + "export const allowanceCss = " + json.dumps(allowance_css()) + ";\n")


if __name__ == "__main__":
    write_fixture(Path(__file__).resolve().parents[1])
